---
title: "Data 607 - HW7"
output: 
  html_document:
    highlight: pygments
    df_print: paged
    theme: lumen
    code_folding: "hide"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r env,include=FALSE}
library(plyr)
library(tidyverse)
library(magrittr)
library(RCurl)
library(XML)
library(jsonlite)
library(kableExtra)
```

## Books Data {.tabset .tabset-fade .tabset-pills}

### XML
```{r xml}
x <- getURL("https://raw.githubusercontent.com/baroncurtin2/data607/master/week7/tables/books.xml")

# show table
#knitr::kable(x)
```


### HTML
```{r html}
h <- getURL("https://raw.githubusercontent.com/baroncurtin2/data607/master/week7/tables/books.html") %>%
  readHTMLTable(header = TRUE, which = 1) %>%
  tbl_df

# show table
knitr::kable(h, "html")%>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```


### JSON
```{r json}
j <- getURL("https://raw.githubusercontent.com/baroncurtin2/data607/master/week7/tables/books.json") %>%
  fromJSON(flatten = TRUE, simplifyDataFrame = TRUE) %>%
  data.frame

# show table
knitr::kable(j)
```

